name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "AIzaSyDbtwV8JVqqiC7fTRaHmOoCEjWn2sYYUP8"
          VITE_FIREBASE_AUTH_DOMAIN: "ozkon-celik-takip.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "ozkon-celik-takip"
          VITE_FIREBASE_STORAGE_BUCKET: "ozkon-celik-takip.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "351331034390"
          VITE_FIREBASE_APP_ID: "1:351331034390:web:5651cab58d7e3b87329c37"

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
